patterns_and_insertions:
    [
        # Use single ticks for regex patterns
        # http://blogs.perl.org/users/tinita/2018/03/strings-in-yaml---to-quote-or-not-to-quote.html
        # You need to escape \ with \\ in the pattern, for instance for \\todo
        # Use Python named groups https://docs.python.org/3/library/re.html#regular-expression-examples
        # Escape {{ and }} in the insertion expression
        # 
        # Optional:
        # Set strip_whitespace to n to disable white space stripping while replacing the pattern. (Default: y)

        {
            "pattern" : '(?:\\figcomp{\s*)(?P<first>.*?)\s*}\s*{\s*(?P<second>.*?)\s*}\s*{\s*(?P<third>.*?)\s*}',
            "insertion" : '\parbox[c]{{ {second} \linewidth}} {{ \includegraphics[width= {third} \linewidth]{{figures/{first} }} }}',
            "description" : "Replace figcomp",
            # "strip_whitespace": n 
        },
    ]
verbose: False
commands_to_delete: [
    'footnote',
    'footnote ',
    'crdata',
    'appendixhead',
    'selectlanguage',
    'name',
    'expandafter',
    'copyrightyear',
    'acmYear',
    'acmBooktitle',
    'acmPrice',
    'authorcontributions',
    'thanksref',
    'funding',
    'conflictsofinterest',
    'externalbibliography',
    'acmDOI',
    'acmISBN',
    'acmConference',
    'titleheader',
    'affil',
    'authorrunning',
    'pagenumbering',
    'enlargethispage',
    'author',
    'AuthorNames',
    'author\n',
    'Author\n',
    'Author',
    'fntext',
    'icmlauthor',
    'icmlauthor\n',
    'icmladdress',
    'icmladdress\n',
    'received',
    'runninghead',
    'bstctlcite',
    'slugger',
    'tocauthor',
    'author\*',
    'vspace\*',
    '\write18',
    'hspace\*',
    'vspace',
    'hspace',
    'maketitle',
    'institute',
    'label',
    'urlstyle',
    'acks',
    'tnoteref',
    'Appendix',
    'urlstyle',
    'url',
    'editor',
    'ccsdesc',
    'cortext',
    'bibliography',
    'permission',
    'usetikzlibrary',
    'thanks',
    'thispagestyle',
    'abovedisplayskip',
    'belowdisplayskip',
    'bibliographystyle',
    'IfSubStringInString',
    'hyphenation',
    'theoremstyle',
    'colorbox',
    'textcolor',
    'color',
    'caption',
    'thlabel',
    'fancyfoot',
    'captionof',
    'settopmatter',
    'IEEEtriggeratref',
    'IEEEauthorblockN',
    'IEEEauthorblockA',
    'IEEEauthorblockN\n',
    'IEEEauthorblockA\n',
    'IEEEauthorrefmark',
    'orcid',
    'typeout',
    'fancyhead',
    'pagestyle',
    'biboptions',
    'affiliation',
    'address',
    'institution',
    'printalgoIEEE',
    'date',
    'authornote',
    'numberofauthors',
    'footnotetext',
    'email',
    'reftitle',
    'setcopyright',
    'ead',
    'deleted',
    'includegraphics',
    'comment',
    'abstract',
    'replaced',
    'xspace',
]
commands_only_to_delete: [
    'titlerunning',
    'runningtitle',
    #'subtitle',
    'title',
    'title\*',
    'accept',
    #'section',
    #'section ',
    #'Section',
    #'SubSection',
    #'SubSubSection',
    'added',
    'icmltitle',
    'textsuperscript',
    #'mysubsubsection',
    #'mysubsection',
    #'mysection',
    'texttt',
    'textsc',
    'textit',
    'mathit',
    'makebox',
    'mbox',
    'textbf',
    'acl',
    'textnormal',
    'texttt ',
    'textsc ',
    'textit ',
    'mathit ',
    'textbf ',
    'gls',
    'Gls',
    'glspl',
    'textnormal ',
    #'section\*',
    'inlinetitle',
    #'section\* ',
    #'chapter',
    #'chapter ',
    #'chapter\*',
    #'chapter\* ',
    'mbox',
    #'subsection',
    #'subsection ',
    #'subsubsection ',
    #'subsubsection',
    #'subsection\*',
    #'subsection\* ',
    #'subsubsection\*',
    #'subsubsection\* ',
    'hl',
    'highlight',
    'IEEEraisesectionheading',
    'IEEEtitleabstractindextext',
    'IEEEPARstart',
    'it',
    'added',
    'paragraph',
    'paragraph\*',
    'MakeLowercase',
    'emph',
    'emph ',
    'text',
    'acp',
    'ac'
    
]
environments_to_delete: [
    #'proof',
    #'IEEEproof',
    'icmlauthorlist',
    #'IEEEkeywords',
    #'keywords',
    #'keyword',
    'tikzpicture',
    'groupplot',
    'biography',
    'IEEEbiographynophoto',
    'acronym',
    'MSCcodes',
    'IEEEbiography',
    'figure',
    'AMS',
    'acknowledgement',
    'acknowledgments',
    'acknowledgements',
    'figure\*',
    'minipage',
    'table',
    'table\*',
    'glist',
    'tabular',
    'tabular\*',
    'center',
    'remark',
    'algorithm',
    'algorithmic',
    'CCSXML',
    'acks',
    'lstlisting',
    'tabu',
    'algorithm\*',
    'algorithmic\*',
    'longtable',
    'sidewaystable\*',
    'sidewaystable',
    'appendices',
    'wrapfigure',
    'appendix'
]
